/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package irrgarten.UI;

import irrgarten.Directions;
import irrgarten.GameState;
import java.awt.Font;

/**
 *
 * @author mariorl
 */
public class GUI extends javax.swing.JFrame implements UI{

    private Cursors cursors;
    private Font fuente = new Font("Arial", Font.PLAIN, 20);
    private Font fuente2 = new Font("Arial", Font.PLAIN, 11);
    /**
     * Creates new form UserUI
     */
    public GUI() {
        initComponents();
        setVisible(true);
        cursors = new Cursors(this,true);
        winner.setVisible(false);
    }

    @Override
    public Directions nextMove(){
        return cursors.getDirection();
    }
    @Override
    public void showGame(GameState gameState){
        gameLogs.setText(gameState.getLog());
        players.setText(gameState.getPlayers());
        players.setFont(fuente2);
        monsters.setText(gameState.getMonsters());
        labyrinth.setText(gameState.getLabyrinth());
        labyrinth.setFont(fuente);
        currentPlayer.setText("Player " + gameState.getCurrentPlayer() + " turn's");
        int siguiente = gameState.getCurrentPlayer()+1;
        nextPlayer.setText("Next player " + siguiente);
        if(gameState.getWinner()){
            winner.setVisible(true);
            winner.setText("Winner " + gameState.getCurrentPlayer());
        }
        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        currentPlayer = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gameLogs = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        labyrinth = new javax.swing.JTextArea();
        winner = new javax.swing.JLabel();
        nextPlayer = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        players = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        monsters = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        currentPlayer.setText("currentPlayer");

        gameLogs.setColumns(20);
        gameLogs.setRows(5);
        jScrollPane1.setViewportView(gameLogs);

        labyrinth.setColumns(20);
        labyrinth.setRows(5);
        jScrollPane2.setViewportView(labyrinth);

        winner.setText("winner");

        nextPlayer.setText("nextPlayer");

        players.setColumns(20);
        players.setRows(5);
        jScrollPane3.setViewportView(players);

        monsters.setColumns(20);
        monsters.setRows(5);
        jScrollPane4.setViewportView(monsters);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nextPlayer)
                    .addComponent(winner)
                    .addComponent(currentPlayer))
                .addGap(300, 300, 300)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 140, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(currentPlayer)
                        .addGap(18, 18, 18)
                        .addComponent(nextPlayer)
                        .addGap(18, 18, 18)
                        .addComponent(winner))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentPlayer;
    private javax.swing.JTextArea gameLogs;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea labyrinth;
    private javax.swing.JTextArea monsters;
    private javax.swing.JLabel nextPlayer;
    private javax.swing.JTextArea players;
    private javax.swing.JLabel winner;
    // End of variables declaration//GEN-END:variables
}
